---
layout: cv
title: Grace Kazmierski's CV
---
# GRACE KAZMIERSKI
Student at BYU - Idaho
<div id="webaddress">
<a href="gkazmierski@byui.edu">gkazmierski@byui.edu</a>
</div>

## Contact
**Phone:** (406) 696-8738  
**Email:** [gracekazzy@gmail.com](mailto:gracekazzy@gmail.com)  
**GitHub:** [github.com/gracekazmierski](https://github.com/gracekazmierski)  
**LinkedIn:** [Grace Kazmierski](https://www.linkedin.com/in/gracekazmierski)

## Summary
I am a highly motivated candidate with a strong background in customer service, strong writing skills, and a big desire to learn. Skilled in problem-solving and communication, I am a critical thinker with strong interpersonal skills and a proven track record of providing customer satisfaction. I have training as a leader in a team environment, as well as experience in individually focused roles.

## Experience

### **Production Baker**  
**Black Dog Coffee House | Billings, MT**  
*MAY 2024 - PRESENT*  
- Prepare a diverse range of baked goods to meet high production demands
- Adapt to high-stakes environments to meet production quotas, quality standards, and health regulations
- Manage time effectively to prioritize tasks, streamline efficiency, and respond promptly to changes in production
- Produce large quantities of baked goods for wholesale distribution

### **Marketing Intern**  
**Utah Tech University | St. George, UT**  
*DECEMBER 2023 – MAY 2024*  
- Designed and created digital graphics to support marketing campaigns
- Conducted research to inform and optimize marketing strategies
- Collaborated on branding projects to align with Utah Tech’s identity and mission statement
- Wrote engaging promotional content for new students and their families

### **Opinion Editor**  
**Sun News Daily | St. George, UT**  
*DECEMBER 2023 – MAY 2024*  
- Edited, advised, and published articles weekly
- Oversaw assignment creation and delegation of tasks to team members while providing feedback
- Managed deadlines to ensure timely delivery
- Maintained style, accuracy, coherence, and alignment with newsletter standards
- Developed creative strategies to increase reader engagement on all platforms

## Education

### **Computer Science Student**  
**Utah Tech University / Brigham Young University - Idaho**  
*AUGUST 2023 - PRESENT*  
- 4.0 GPA
- Computing Society

## Skills & Technologies
- Python
- Programming with Classes in C#
- Data Visualization
- Web Development (CSS, HTML5, JavaScript)
- Technical Teamwork
- Machine Learning
- SQL
- Tableau


### **Soft Skills**
- Leadership
- Adaptability
- Time Management
- Collaboration
- Creativity
- Attention to Detail
- Problem-Solving
- Communication

<!-- ### Footer

Last updated: May 2013 -->